
export const PASSWORD_LENGTH_ERROR = "PASSWORD_LENGTH_ERROR";
export const PASSWORD_CONFIRM_MISMATCH = "PASSWORD_CONFIRM_MISMATCH";
export const PASSWORD_NOT_SECURE = "PASSWORD_NOT_SECURE";
export const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
export const ACCESS_TOKEN_EXPIRE = "ACCESS_TOKEN_EXPIRE";
